version: '3.8'
services:
  postgres:
    container_name: "picture-room-postgres-clj"
    networks:
      - picture-room-clj
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: picture-room
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=500'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
volumes:
  pg-data:

networks:
  picture-room-clj:
