-- :name create-products-table
-- :command :execute
-- :result :raw
-- :doc creates products table
create table if not exists products
(
    id                         bigserial primary key,
    created_at                 timestamptz not null default now(),
    updated_at                 timestamptz not null default now(),
    deleted_at                 timestamptz,
    name                       varchar(128) not null default '',
    type                       varchar(128) not null default '',
    sku                        varchar(128) not null default '',
    description                varchar(5120) not null default '',
    weight                     double precision not null default 0,
    depth                      double precision not null default 0,
    height                     double precision not null default 0,
    price                      double precision not null default 0,
    cost_price                 double precision not null default 0,
    retail_price               double precision not null default 0,
    sale_price                 double precision not null default 0,
    map_price                  double precision not null default 0,
    tax_class_id               int8 not null default 0,
    product_tax_code           varchar(32) not null default '',
    calculated_price           double precision not null default 0.0,
    categories                 int8[],
    brand_id                   int8 not null default 0,
    option_set_id              int8 not null default 0,
    option_set_display         varchar(32) not null default '',
    inventory_level            int8 not null default 0,
    inventory_warning_level    int8 not null default 0,
    inventory_tracking         varchar(32) not null default '',
    reviews_rating_sum         int8 not null default 0,
    reviews_count              int8 not null default 0,
    total_sold                 int8 not null default 0,
    fixed_cost_shipping_price  double precision not null default 0,
    is_free_shipping           bool not null default false,
    is_visible                 bool not null default false,
    is_featured                bool not null default false,
    warranty                   varchar(256) not null default '',
    bin_picking_number         varchar(128) not null default '',
    layout_file                varchar(128) not null default '',
    upc                        varchar(128) not null default '',
    mpn                        varchar(128) not null default '',
    gtin                       varchar(128) not null default '',
    search_keywords            varchar(128) not null default '',
    availability               varchar(128) not null default '',
    availability_description   varchar(2048) not null default '',
    gift_wrapping_options_type varchar(128) not null default '',
    sort_order                 int8 not null default 0,
    condition                  varchar(2048) not null default '',
    is_condition_shown         bool not null default false,
    order_quantity_minimum     int8 not null default 0,
    order_quantity_maximum     int8 not null default 0,
    page_title                 varchar(512) not null default '',
    meta_description           varchar(1024) not null default '',
    date_created               varchar(128) not null default '',
    date_modified              varchar(128) not null default '',
    view_count                 int8 not null default 0,
    preorder_release_date      varchar(128) not null default '',
    preorder_message           varchar(2048) not null default '',
    is_preorder_only           bool not null default false,
    is_price_hidden            bool not null default false,
    price_hidden_label         varchar(2048) not null default '',
    base_variant_id            int8 not null default 0,
    custom_url                 jsonb not null default '{}'
);

-- :name create-product! :<!
-- :doc creates a new product record
insert into products (
  id,
  created_at,
  updated_at,
  deleted_at,
  name,
  type,
  sku,
  description,
  weight,
  depth,
  height,
  price,
  cost_price,
  retail_price,
  sale_price,
  map_price,
  tax_class_id,
  product_tax_code,
  calculated_price,
  categories,
  brand_id,
  option_set_id,
  option_set_display,
  inventory_level,
  inventory_warning_level,
  inventory_tracking,
  reviews_rating_sum,
  reviews_count,
  total_sold,
  fixed_cost_shipping_price,
  is_free_shipping,
  is_visible,
  is_featured,
  warranty,
  bin_picking_number,
  layout_file,
  upc,
  mpn,
  gtin,
  search_keywords,
  availability,
  availability_description,
  gift_wrapping_options_type,
  sort_order,
  condition,
  is_condition_shown,
  order_quantity_minimum,
  order_quantity_maximum,
  page_title,
  meta_description,
  date_created,
  date_modified,
  view_count,
  preorder_release_date,
  preorder_message,
  is_preorder_only,
  is_price_hidden,
  price_hidden_label,
  base_variant_id,
  custom_url
) values (
  :id,
  :created_at,
  :updated_at,
  :deleted_at,
  :name,
  :type,
  :sku,
  :description,
  :weight,
  :depth,
  :height,
  :price,
  :cost_price,
  :retail_price,
  :sale_price,
  :map_price,
  :tax_class_id,
  :product_tax_code,
  :calculated_price,
  :categories,
  :brand_id,
  :option_set_id,
  :option_set_display,
  :inventory_level,
  :inventory_warning_level,
  :inventory_tracking,
  :reviews_rating_sum,
  :reviews_count,
  :total_sold,
  :fixed_cost_shipping_price,
  :is_free_shipping,
  :is_visible,
  :is_featured,
  :warranty,
  :bin_picking_number,
  :layout_file,
  :upc,
  :mpn,
  :gtin,
  :search_keywords,
  :availability,
  :availability_description,
  :gift_wrapping_options_type,
  :sort_order,
  :condition,
  :is_condition_shown,
  :order_quantity_minimum,
  :order_quantity_maximum,
  :page_title,
  :meta_description,
  :date_created,
  :date_modified,
  :view_count,
  :preorder_release_date,
  :preorder_message,
  :is_preorder_only,
  :is_price_hidden,
  :price_hidden_label,
  :base_variant_id,
  :custom_url
) on conflict (id) do update set
  updated_at                 = now(),
  name                       = :name,
  type                       = :type,
  sku                        = :sku,
  description                = :description,
  weight                     = :weight,
  depth                      = :depth,
  height                     = :height,
  price                      = :price,
  cost_price                 = :cost_price,
  retail_price               = :retail_price,
  sale_price                 = :sale_price,
  map_price                  = :map_price,
  tax_class_id               = :tax_class_id,
  product_tax_code           = :product_tax_code,
  calculated_price           = :calculated_price,
  categories                 = :categories,
  brand_id                   = :brand_id,
  option_set_id              = :option_set_id,
  option_set_display         = :option_set_display,
  inventory_level            = :inventory_level,
  inventory_warning_level    = :inventory_warning_level,
  inventory_tracking         = :inventory_tracking,
  reviews_rating_sum         = :reviews_rating_sum,
  reviews_count              = :reviews_count,
  total_sold                 = :total_sold,
  fixed_cost_shipping_price  = :fixed_cost_shipping_price,
  is_free_shipping           = :is_free_shipping,
  is_visible                 = :is_visible,
  is_featured                = :is_featured,
  warranty                   = :warranty,
  bin_picking_number         = :bin_picking_number,
  layout_file                = :layout_file,
  upc                        = :upc,
  mpn                        = :mpn,
  gtin                       = :gtin,
  search_keywords            = :search_keywords,
  availability               = :availability,
  availability_description   = :availability_description,
  gift_wrapping_options_type = :gift_wrapping_options_type,
  sort_order                 = :sort_order,
  condition                  = :condition,
  is_condition_shown         = :is_condition_shown,
  order_quantity_minimum     = :order_quantity_minimum,
  order_quantity_maximum     = :order_quantity_maximum,
  page_title                 = :page_title,
  meta_description           = :meta_description,
  date_created               = :date_created,
  date_modified              = :date_modified,
  view_count                 = :view_count,
  preorder_release_date      = :preorder_release_date,
  preorder_message           = :preorder_message,
  is_preorder_only           = :is_preorder_only,
  is_price_hidden            = :is_price_hidden,
  price_hidden_label         = :price_hidden_label,
  base_variant_id            = :base_variant_id,
  custom_url                 = :custom_url

  returning *;

-- :name get-products :? :*
-- :doc retrieves all product records
select * from products;

-- :name get-product :? :1
-- :doc retrieves a product record by id
select * from products
where id = :id;
